import {
  // product_01,
  product_1,
  product_2,
  product_3,
  product_4,
  product_5,
  product_6,
  product_7,
  product_8,
  product_9,
  product_10,
} from "../assets/images/products";

export const productList = [
  {
    id: 1,
    product_name: "เซ็ตดูแลผิว",
    product_img: product_1,
    category_id: 1,
    category_name: "cleanser",
    price: 357,
    stock: 999,
  },
  {
    id: 2,
    product_name: "คลีนซิ่งเลิฟ",
    product_img: product_2,
    category_id: 3,
    category_name: "cleansing",
    price: 290,
    stock: 999,
  },
  {
    id: 3,
    product_name: "สบู่เกรปโซป",
    product_img: product_3,
    category_id: 4,
    category_name: "cleanser",
    price: 150,
    stock: 999,
  },
  {
    id: 4,
    product_name: "เซรั่มเลิฟ",
    product_img: product_4,
    category_id: 6,
    category_name: "serum",
    price: 179,
    stock: 999,
  },
  {
    id: 5,
    product_name: "กันแดด Sun Kiss",
    product_img: product_4,
    category_id: 5,
    category_name: "sun_cream",
    price: 290,
    stock: 999,
  },
  {
    id: 6,
    product_name: "ครีมแคคตัส",
    product_img: product_6,
    category_id: 1,
    category_name: "cream",
    price: 69,
    stock: 999,
  },
  {
    id: 7,
    product_name: "เซตลดสิว",
    product_img: product_7,
    category_id: 7,
    category_name: "set",
    price: 600,
    stock: 999,
  },
  {
    id: 8,
    product_name: "เซตหน้านุ่มลดสิว",
    product_img: product_8,
    category_id: 7,
    category_name: "set",
    price: 680,
    stock: 999,
  },
  {
    id: 9,
    product_name: "Healing Factor",
    product_img: product_9,
    category_id: 7,
    category_name: "set",
    price: 840,
    stock: 999,
  },
  {
    id: 10,
    product_name: "Combo Set",
    product_img: product_10,
    category_id: 7,
    category_name: "set",
    price: 990,
    stock: 999,
  },
];
